### ISSUE TITLE
Getters and Setters 

### ISSUE THREAD

**Issue by IgorKulishov** [g1er/Andrew#10]
## Getters and Setters of Classes:
В прошлой теме мы изучили синтакс нового JavaScript ES6 - как создавать классы содержащие методы и свойства, а так же образовывать новые объекты используя эти классы.

Мы продолжим изучать дальше различные виды этих методов.
На этот раз мы изучим как читать и менять/задавать внутренние свойства объектов при помощи getter и setter соотеветственно. 
**Итак приведу пример:**
```
//определение класса
class User {
  constructor(firstName) {
    this.firstName = firstName;
  }
  // getter - метод для получения/чтения значений внутренних свойства (обозначается словом "get")
  get fullName() {
    return this.firstName;
  }
  // "set" - setter - метод для задания значений внутренных свойств (обозначается словом "set")
  set fullName(newValue) {
    this.firstName = newValue;
  }
};
var user = new User("Robin");
//обращаемся к гетеру
alert(user.fullName);
//обращаемся к сетеру
user.fullName = "Bobin";
//обращаемся еще раз к гетеру и читаем новые свойства
alert(user.fulName);
```
Основные моменты:
1) getter обозначаются при помощи слова get перед методом
2) setter обозначаются при помощи слова set перед методом
3) при обращении к гетеру нового объекта не используем скобки вконце getter метода 
4) так же при задании значений созданного объекта через setter мы присваиваем методу setter новое значение как будто бы обычному свойству объекта:
`
user.fullName = "Bobin";
`
> Обращаю внимание мы не помещаем новое значение как аргумент внутри скобок метода setter как могло бы показаться (т.е. неправильно было бы: user.fullName("Bobin") )

Кроме того обращаю внимание что, называние getter и setter не обязательно должно быть одинаковым.

**Comment by IgorKulishov** [comment]
Для прароботки упражнений можешь использовать консоли браузеров (все современные браузеры поддерживают JavaScript ES6) 
Кроме того есть такие online песочницы: https://jsbin.com/junibalupu/4/edit?html,css,js,output

**Comment by g1er** [comment]
Значит, как я понял, prototype у нас для добавления новых свойств и методов, а get и set для получения и изменения их значений.
А как мне изменить значение новосозданного через prototype свойства или метода через set? Например, я создаю новое свойство через User.prototype, а потом мне надо его значение изменить. Как мне это осуществить?

**Comment by IgorKulishov** [comment]
Привет не совесем так: да действительно при помощи prototype ты можешь добавлять новые методы и свойства. Так же правильно что get для получения и set для задания нового значения свойства. Однако тут есть важная поправка: get и set являются по сути так же методами и кроме того так же как и все остальные методы так же содержатся внутри prototype (что ты можешь легко проверить если скопируешь определение класса из примера из объяснения выше в консоле браузера нажмешь Enter. После чего нажмешь на треугольник и откроешь свойства класса в котором если ты раскроешь prototype ты увидешь там внути get и set. Надо помнить что под капотом JS ES6 это все тот же ES5 get и set так же задаются внутри prototype.

**Comment by IgorKulishov** [comment]
**Пример применения, через get/set , prototype и Object.defineProperty :**

```
//определим методы в класса через get и set
class MyCount {
  constructor(num) {
    this.num = num;

  }
   get read() { return this.num };
   set add(x) { this.num  += x };
}
let myCounter = new MyCount(1)
myCounter.add = 3
console.log(myCounter.read);
myCounter.add = 4
console.log(myCounter.read);

//добавим новый метод через prototype
MyCount.prototype.multiply = function(y) {
   return this.num *= y;
}
myCounter.multiply(2);
console.log(myCounter.read)

//Используем Object.defineProperty встроенный метод JavaScript для добавления класса в prototype: 
// полное описание на официальном сайте: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

Object.defineProperty(MyCount.prototype, "subtract", {
  set(subtract) {
    this.num -= subtract;
  }
});

var a = new MyCount(123);

a.add = 0;
a.subtract = 2
console.log(a.read); 

```

> Добавь дополнительно свой метод любым способом

**Comment by g1er** [comment]
//ну, пусть будет квадратный корень
MyCount.prototype.squareRoot = function(s) {
return Math.sqrt(this.num)= s;
}
myCounter.squareRoot(4);
console.log(myCounter.read);

**Comment by g1er** [comment]
хмм... знаешь, проверил это в консоли дебаггера, и он мне выдал такую ошибку:
`Identifier 'MyCount' has already been declared at <anonymous>:1:1`
я вбил твой пример:
```
class MyCount {
  constructor(num) {
    this.num = num;

  }
   get read() { return this.num };
   set add(x) { this.num  += x };
}
let myCounter = new MyCount(1)
myCounter.add = 3
console.log(myCounter.read);

//добавим новый метод через prototype
MyCount.prototype.multiply = function(y) {
   return this.num *= y;
}
myCounter.multiply(2);
console.log(myCounter.read)
```
но и тут был тот же результат. что-то я не пойму, в чем нестыковка?

**Comment by g1er** [comment]
Я нашел в чем причина. Плюс видать я ещё и с синтаксисом напутал. Вот измененный вариант:

MyCount.prorotype.division = function(s) {
return this.num /= s;
}

myCounter.division(3);
console.log(myCounter.read);

Тут при проверке в консоли все происходит нормально

**Comment by IgorKulishov** [comment]
Ошибка:
```
Identifier 'MyCount' has already been declared at <anonymous>:1:1
```
появляется когда дважды пытаешься определить один и тот же класс - не позволяет повторно опрелить класс с тем же названием в том же окне. Если ты хочешь переопределить класс, то пожалуйста переназови класс (дай другое название).
Или открой другое окно.

**Comment by g1er** [comment]
Я так и понял. Я просто не разобрался в работе дебагера, думал надо каждый раз заново определять класс после каждого нажатия Enter

**Comment by IgorKulishov** [comment]
Предлагаю еще раз просмотреть, задать если есть вопросы. И если все понятно закрыть задание и перейти к следующему.
