### ISSUE TITLE
asynchronous call  

### ISSUE THREAD

**Issue by IgorKulishov** [g1er/Andrew#2]
Задание:
Выполнить асинхронную загрузку данных используя встроенный метод XMLHttpRequest:
I. создать backgroundReadFile:
```
function backgroundReadFile(url, callback) {
  var req = new XMLHttpRequest();
  req.open("GET", url, true);
  req.addEventListener("load", function() {
    if (req.status < 400)
      callback(req.responseText);
  });
  req.send(null);
}

```
II. обернуть backgroundReadFile в try catch и подставить значение callback:
```
try {
  backgroundReadFile("https://jsonplaceholder.typicode.com/posts/1", function(data) {
    if (!data)
      throw new Error("That was unexpected");
    else
      console.log(data);
  });
} catch (e) {
  console.log("Hello from the catch block");
}

```
Примечание:
1) Теория: Если третьим аргументом open мы передадим true, запрос будет асинхронным. 
Это значит, что при вызове send запрос ставится в очередь на отправку. 
Программа продолжает работать, а браузер позаботиться об отправке и получении данных в фоновом режиме (т.е. пока не пришел ответ с сервера, браузер может выполнять другие ф-ции, как только придет ответ с сервера, браузер вновь вернется к дальнейшему выполнению данной ф-ции).
2) URL: Для теста взят открытый (public) тестовый url: https://jsonplaceholder.typicode.com/posts/1,
который выдает REST (можешь попробовать в браузере)
3) Выполнить задание в консоле браузера ``

**Comment by IgorKulishov** [comment]
Задание:
Выполнить асинхронную загрузку данных используя встроенный метод XMLHttpRequest:
I. создать backgroundReadFile:
function backgroundReadFile(url, callback) {
  var req = new XMLHttpRequest();
  req.open("GET", url, true);
  req.addEventListener("load", function() {
    if (req.status < 400)
      callback(req.responseText);
  });
  req.send(null);
}

II. обернуть backgroundReadFile в try catch и подставить значение callback:
try {
  backgroundReadFile("https://jsonplaceholder.typicode.com/posts/1", function(data) {
    if (!data)
      throw new Error("That was unexpected");
    else
      console.log(data);
  });
} catch (e) {
  console.log("Hello from the catch block");
}

Примечание:
1) Теория: Если третьим аргументом open мы передадим true, запрос будет асинхронным. 
Это значит, что при вызове send запрос ставится в очередь на отправку. 
Программа продолжает работать, а браузер позаботиться об отправке и получении данных в фоне.
2) URL: Для теста взят открытый (public) тестовый url: https://jsonplaceholder.typicode.com/posts/1,
который выдает REST (можешь попробовать в браузере)
3) Выполнить задание в консоле браузера

**Comment by g1er** [comment]
Привет.
Я немного затупил... У меня вывелось в консоль "Hello from the catch block", потому что backgroundReadFile - undefined. Не могу понять, почему он считается неопределенным? Потому, что значение data не определено?
Я перечитал снова твои объяснения, но вот с этими значениями функций в скобках я не могу разобраться. И я также не могу понять, часть II это та же часть I, обернутая в try catch, или это отдельная часть?
Я видимо слишком много времени упустил, потому, что сейчас не могу нормально связать концы с концами.

**Comment by IgorKulishov** [comment]
Перед выполнением необходимо одновременно скопировать I и II в Console. 
Для добавления строки после I необходимо нажимать Shift + Enter  (в таком случае будет добавлена строка, а не выполнение функции ).

**Comment by IgorKulishov** [comment]
'"Hello from the catch block", потому что backgroundReadFile - undefined' : это означает, что backgroundReadFile не определена как функция в блоке II, поэтому необходимо (как я написал выше) до выполнения (нажатия Enter) перед блоком II обязательно скопировать блок I.

**Comment by IgorKulishov** [comment]
![async_get_call](https://user-images.githubusercontent.com/6174568/35367356-e6ea94cc-014b-11e8-967b-9f9d994f2aff.png)

**Comment by IgorKulishov** [comment]
![async_get_call](https://user-images.githubusercontent.com/6174568/35367859-9f30e3b8-014e-11e8-94a6-71b9c09df1b9.png)

**Comment by IgorKulishov** [comment]
![async_get_call](https://user-images.githubusercontent.com/6174568/35367980-1f21f026-014f-11e8-8584-0d594abbe231.png)

**Comment by IgorKulishov** [comment]
Дополнительно можешь почитать об addEventListener в той же книге:
https://habrahabr.ru/post/244041/
Мы в нашем примере слушаем событие "load" - что означает окончание загрузки информации полученной от сервера. 
Мы регистрируем "слушатель события "load" " к объекту req, таким образом как только отправленный объектом req запрос на сервер вернется, вызовется выражение ф-ии определенное в методе .addEventlistener.

**Comment by g1er** [comment]
Сегодня все получилось. Я получил в консоль сообщение.
Что интересно, в прошлый раз я сделал в принципе то же самое, только не в консоль, а в отдельный html-файл, и потом запустил его в браузере. Но результат был другим, тем, который я тебе присылал. Сегодня, после того, как у меня получилось в консоли, я снова открыл тот файл, ничего в нем не меняя, и вуаля, он сработал как надо.
Возможно, именно это сбило меня с толку в прошлый раз. Я начал копаться в коде, пытаться разобраться, и еще больше запутался в итоге. Кстати, не первый раз замечаю, что браузер так ведет себя. Я пишу код, проверяю в баузере, браузер молчит, ничего не делает, и ошибку тоже не пишет. Я бьюсь над кодом в поиске любых ошибок, ворошу гугл, 10 раз перезагружаю окно, в том числе вместе с кэшем страницы, в итоге бросаю все и закрываю. Через некоторое время с восстановленными нервами я снова сажусь разбирать код. Ничего не исправляя, я запускаю прежний код, и вдруг он начинает исправно работать, как надо. Не знаю, что это за волшебство, но периодически случается.
