### ISSUE TITLE
Взаимодействие между компонентами

### ISSUE THREAD

**Issue by g1er** [g1er/Andrew#33]
В общем такая у меня загвоздка.
Я сейчас остановился на теме взаимодействия между компонентами, когда в одном главном компоненте app.component сочетаются несколько дочерних, которые должны обмениваться данными. В курсе это Блок 3 Урок 2. 
Так вот. В предыдущих уроках в качестве тестового задания для самого себя, я сделал простую форму, в которой надо вписать твои Имя, стиль плавания и дистанцию, и тебя добавит в стартовый список. До этого я реализовал это все в одном компоненте, и все успешно работало. Рабочий образец лежит [тут](https://github.com/g1er/Andrew/tree/develop-andrey/angular/develop-andrey) в ветке develop-andrey. Он состоит из 3х полей ввода, куда надо внести информацию, с кнопкой, которая запускает функцию, и массива объектов, который перебирается с помощью итерации *ngFor и куда добавляется новый объект, создаваемый при введении данных в вышеперечисленные поля при нажатии кнопки. 
В качестве тренировки в последнем уроке, который я указал, я решил разделить это дело на 2 компонента: на компонент со строками ввода и кнопкой, и на компонент со списком объектов. И, основываясь на данных из урока, я попытался наладить их взаимодействие с помощью EventEmitter. Но вот беда: вроде сделал все как в уроке, но форма уже не работает. Я долго сам ковырялся, пересматривал урок несколько раз, читал инфу в сторонних источниках. В итоге я запутался уже, плюс голова уже не работает, т.к. у нас тут уже час ночи. Поэтому не мог бы ты посмотреть то, что я сделал, и разъяснить мне, в чем я промахнулся? Переделанный код я залил на новую ветку testRoom-andrey [сюда](https://github.com/g1er/Andrew/tree/testRoom-andrey/angular/develop-andrey). Когда разберусь с проблемой, я эту ветку солью с develop-andrey, а пока для наглядности разделил.

Если тебе надо время, я не напрягаю. Посмотри, когда будет время. Просто я не могу перешагнуть через эту тему, не разобравшись, оставить, типа потом в процессе разберусь, потому, что как мне кажется это достаточно важная тема. Поэтому мне надо тут все понять, хотя бы саму логику и последовательность, чтобы идти дальше. А уж синтаксис всегда можно подглядеть.
Спасибо заранее />

**Comment by IgorKulishov** [comment]
Бро привет,
Посмотри пожалуйста merge request
https://github.com/g1er/Andrew/pull/34/files с моими объяснениями.
Я не успел запустить и проверить.
Дай знать пожалуйста помогло ли это и есть ли вопросы.
Удачи, Игорь!

**Comment by IgorKulishov** [comment]
Спасибо большое за вопрос.
Я создал merge request https://github.com/g1er/Andrew/pull/34/files
Я не успел запустить и проверить.
Дай знать если это помогло и если есть вопросы.

**Comment by IgorKulishov** [comment]
В целом ты делаешь прогресс!
И мне очень нравиться твой стиль.
Молодец - продолжай учиться.
Нет предела совершенству и поверь бывает что я трачу недели  на один вопрос.
Так мы грызем гранит и к сожалению нет другого пути (кроме грызть по
возможности используя все доступные источники информации включая поиск в
нете и конечно же спрашивай будем работать вместе).
Успехов тебе Бро!

2018-07-29 2:58 GMT-04:00 Igor Kulishov <igorkulishov@gmail.com>:

> Бро привет,
> Посмотри пожалуйста merge request https://github.com/
> g1er/Andrew/pull/34/files с моими объяснениями.
> Я не успел запустить и проверить.
> Дай знать пожалуйста помогло ли это и есть ли вопросы.
> Удачи, Игорь!
>

**Comment by g1er** [comment]
Да, помогло, спасибо.
Хотя до конца я все еще на 100% не осознал что как, но дальше сам разберусь. Чувствую, я к этой теме еще не раз буду возвращаться. Но так будет легче, от обратного, зная точно, что все работает как надо, разобраться, почему оно работает.
