### ISSUE TITLE
Promise example

### ISSUE THREAD

**Issue by IgorKulishov** [g1er/Andrew#4]
## Пример на Promise взятый из книги 
**Теперь тоже самое только с примером обращения на сервер помещенного в Promise (из книги: https://habrahabr.ru/post/245145/)**
```
// определение ф-ции:
function get(url) {
  return new Promise(function(succeed, fail) {
    var req = new XMLHttpRequest();
    req.open("GET", url, true);
    req.addEventListener("load", function() {
      if (req.status < 400)
        succeed(req.responseText);
      else
        fail(new Error("Request failed: " + req.statusText));
    });
    req.addEventListener("error", function() {
      fail(new Error("Network error"));
    });
    req.send(null);
  });
}
// получение и обработки ответа
get("example/data.txt").then(function(text) {
  console.log("data.txt: " + text);
}, function(error) {
  console.log("Failed to fetch data.txt: " + error);
}); 
```

**Comment by IgorKulishov** [comment]
Этот пример мы применим в проекте. Задание посмотреть и разобрать логику, задать вопросы если есть.

**Comment by IgorKulishov** [comment]
Обращаю внимание что "req.addEventListener" - это  JavaScript встроенный event listener (слушатель событий).   Event listener (слушатель событий) имеет два аргумента: 
а) string (строка) - предопределенное событие, которые мы слушаем и выполняем ф-цию (второй аргумент). Это ограниченный перечень событий из которого мы определяем интересующее нас событие.
К примеру события могут быть: 
  "click" - нажатие кнопки мышки
   "mousemove" - мышкой провести над опредленным элементом
  "load" - окончание загрузки определенного файла 
Примеры применения на сайте: https://www.w3schools.com/js/js_htmldom_eventlistener.asp
Более полный перечень возможных событий есть на сайте https://www.w3schools.com/jsref/dom_obj_event.asp
Если обратил внимание некоторые начинаются с приставки on: "onclick", "onload"  и т.д.   
б) функция (callback) которая выполняется когда наступает событие (event)

**Comment by g1er** [comment]
Как я понял этот пример:
создаем функцию, внутри которой создаем новый класс Promise, внутри котрого создаем новый XML запрос. Этот запрос мы открываем, определяем ему метод GET и определяем, что это будет асинхронный запрос. Добавляем слушатель событий на событие загрузка, который выведет нам либо что все нормально, либо что есть ошибка. Также добавляем слушатель на событие ошибка, который в случае ошибки выведет нам информацию о ней. И отправляем запрос.
Ну и получение ответа, который выведется в консоли, либо ответ, либо данные об ошибке.
Как-то так />

**Comment by IgorKulishov** [comment]
Da, tolko dobavlyu chto dlya razresheniya/zaversheniya nachatogo "promise" my ispolzuem argumenty success i fail: "Promise(function(**succeed**, **fail**){..})"
