### ISSUE TITLE
Встроенный метод fetch

### ISSUE THREAD

**Issue by IgorKulishov** [g1er/Andrew#5]
Поскольку метод GET (для получения данных с удаленного сервера) используется очень часто, недавно JavaScript версии 6 (ES6) включил готовый метод который упрощает обращение к удаленному серверу. Этот метод асинхронный с использованием Promise "под капотом".
Метод выглядит очень просто:
```
fetch('https://jsonplaceholder.typicode.com/posts/1')
  .then(
    function(response) {
         // do something here with 'response' var
         console.log(response)
    }
  )
  .catch(function(err) {
       //catch error and use 'err' arg to show error message to user
      console.log('catched error: ', err);
  });
```

**Comment by IgorKulishov** [comment]
Так же можешь запустить его в консоле браузера предварительно открыв пустую страницу браузера что бы не было конфликта при обращении на сервер.

**Comment by IgorKulishov** [comment]
В блок "catch" попадают ошибки:  
```
.catch(function(err) {
       //catch error and use 'err' arg to show error message to user
      console.log('catched error: ', err);
  });
```
можешь попробовать указато неправильный url что бы увидеть как работает catch.

**Comment by g1er** [comment]
Интересный вариант. Похож на функцию библиотеки, типа jQuery. Собрал необходимый функционал в один метод

**Comment by IgorKulishov** [comment]
Обращаю внимание что он только GET метод
