### ISSUE TITLE
Прототипы

### ISSUE THREAD

**Issue by IgorKulishov** [g1er/Andrew#8]
## Прототипы
"В дополнение к набору свойств, у всех конструкторов / классов в JavaScript есть свойство **prototype** ("прототип"), которое содержит набор свойств, которые будут унаследованы новыми объектами создаными на основе этих конструкторов / классов. 
Примечание: термин "класс" был введен в версии JavaScript ES6 для того что бы создать схожий с объектно-ориентированных языками синтаксис (название Class используется в Java, C# ).

Объекты созданные на базе конструкторов содержат свойство :
```
__proto__
```
это свойство показывается историю происхождения.

**Далее приведем примеры :**
1) Откроем консоль и скопируем конструктор созданный тобою в предыдущем задании.
```
function Swimmer(style, distance) {
	this.style = style;
	this.distance = function() {
		console.log("This swimmer prefer " + distance + " " + this.style)
    }
}
```
Далее вызовем свойство конструктора prototype:
```
Swimmer.prototype
```
Раскрой полученный объект - ты увидешь что там содержатся объекты: "constructor" и внутри его свойства "prototype".

2) Теперь создадим объект lamer на основе конструктора Swimmer
```
var lamer = new Swimmer('snaky', 10);
```
После чего просмотрим свойства объекта:

```
lamer.__proto__
```
 - это свойство любого объекта (два нижних подчеркивания с обоих сторон) созданного на основе конструктора / класса, содержит свойства проторип конструктора от которого он произошел.

Это свойство не используется на прямую и как правило только используется браузером.
Не рекомендуется использовать на прямую это свойство в коде.

3) Добавим теперь по одному новому свойству и метод в существующий конструктор Swimmer используя следующий синтез:

```
Swimmer.prototype.record = ' world record ';
Swimmer.prototype.training = function() {
   console.log('To get ' + this.record + ' for ' + this.style + ' takes efforts ');
}

lamer.record;

lamer.training();
```

Как мы видем новые свойство и метод объекта доступны несмотря на то что объект был определен ранее (до того как были присвоены новые свойство и метод). 

Поробуй с разными объектами, напиши свои вопросы.

**Comment by g1er** [comment]
Когда я изучал JS, я проходил этот prototype. Как мне объясняли (в более простой форме), он используется для того, чтобы создавать/добавлять дополнительные свойства и функции к классу, от которого потом создаются объекты. Т.е. если мы напишем 
`Swimmer.prototype.record = "New World Record";`
то свойство record появится и у lamer, и у bflySwimmer, и у всех остальных.
Но тогда в чем отличие от того, что мы можем подняться наверх, где мы создавали класс Swimmer, и прописать там свойство record? Или по сути это одно и то же?

А насчет __proto__ я раньше ничего не слышал. Он на практике вообще используется или существует просто для того, чтобы при необходимости к нему обратиться?

**Comment by IgorKulishov** [comment]
Да, совершенно верно, тебе правильно объяснили и ты правильно понял.
Я понимаю твой вопрос - ты правильно понял что свойства "record" можно определить как внутри конструктора так и добавив отдельно после того как определен конструктор при помощи Swimmer.prototype.record.
Тем не менее важно понимать что в JavaScript понятие класса / конструктора отличается от понятия классов в ОО (объектно-ориентированных) языках.
Так в ОО после того как был создан объект от конструктора, свойства созданых объектов не будут меняться если мы добавим новые свойства в конструктор. В JavaScript как ты видешь мы можем добавить свойство в конструктор через prototype - после чего меняются свойства ранее образованных объектров.
В JavaScript "классы" введены для грубого подражания ОО языкам.

**Comment by IgorKulishov** [comment]
Cмотри объяснение 
```__proto__
``` выше - я обновил текст

**Comment by IgorKulishov** [comment]
Важно отметить что если при помощи конструктора и его аргументов удобно создавать уникальные значения свойств новых объектов , то при помощи prototype удобно создавать свойства с общими значениями которые можно делить среди объектов.

**Comment by IgorKulishov** [comment]
Еще интересный оператор, который возвращает протип конструктора конструктора который его создал: "Object.getPrototypeOf(objectName)".
Можно провести интересный эксперимент
а) извлечь прототив из lamer :Object.getPrototypeOf(lamer)
b) добавить свойство через prototype: 
Swimmer.prototype.weight = function(weight) {
 return weight;
}
c) еще раз извлечь прототив из lamer :Object.getPrototypeOf(lamer)
На этот раз мы увидем что добавился weight: f

**Comment by IgorKulishov** [comment]
Пиши если есть вопросы.
Можешь почитать раздел книги для глубины познаний https://habrahabr.ru/post/241587/
Но имей ввиду что, но мы будем изучать TypeScript, который имеет стиль ОО программирования (менее похожий на JavaScript и более Java).
